name: Find Channel

on:
  workflow_dispatch:  #می‌تونید دستی اجراش کنین

jobs:
  find:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pytube
        run: pip install -r requirements.txt

      - name: Run script
        env:
          VIDEO_URL: "https://youtu.be/ZLaA58ANTck"   # 👈 همینی که می‌خواستی: یه متغیر ساده
        run: python yt.py
